resolver: lts-14.9

packages:
  - demo
  # uncomment for quick development of local hadui
  # - ../hadui/hadui

extra-deps:
  - github: complyue/hadui
    commit: stable
    subdirs:
      - hadui

  # need this line until network-3.x goes into lts
  - network-3.1.1.0

compiler-check: newer-minor
