resolver: lts-14.14

packages:
  - hadui-demo

extra-deps:
  # to use a version of Hadui from github
  - url: https://github.com/complyue/hadui/archive/0.1.0.rc1.tar.gz
    subdirs:
      - hadui

  # to use the version of Hadui checked out locally
  # - ../hadui/hadui

system-ghc: true
nix:
  enable: false
