resolver: lts-14.11

packages:
  - demo

extra-deps:
  # to use the version of hadui checked out locally
  #- ../hadui/hadui

  # to use a version of hadui from github
  - github: complyue/hadui
    commit: f7c74c9b3c6ff8625bfbf6317ca3106495e54f33
    subdirs:
      - hadui

  # need this line until network-3.x goes into lts
  - network-3.1.1.0

compiler-check: newer-minor
