resolver: lts-14.11

packages:
  - demo

extra-deps:
  # to use the version of hadui checked out locally
  #- ../hadui/hadui

  # to use a version of hadui from github
  - github: complyue/hadui
    commit: ce82b4f697baeef375c0b35401be523b559b13b0
    subdirs:
      - hadui

  # need this line until network-3.x goes into lts
  - network-3.1.1.0

compiler-check: newer-minor
