resolver: lts-14.9

packages:
  - demo

  # uncomment for quick development of local hadui
  - ../hadui/hadui

  - ../hadui/network
  - ../hadui/websockets

extra-deps:
  #   - github: complyue/hadui
  #     commit: 582a00b0365498c9b4133158a273e8c4a34790fa
  #     subdirs:
  #       - hadui
  # need this line until network-3.x goes into lts
#   - network-3.1.1.0

compiler-check: newer-minor
