name: hadui-demo
version: 0.1.0.0
github: complyue/hadui
license: BSD3
author: Compl Yue
maintainer: compl.yue@icloud.com
copyright: 2019 Compl Yue

extra-source-files:
  - README.md

synopsis: demo for interactive stack project with hadui
category: Demo

description: Please see the README on Github at <https://github.com/complyue/hadui-demo>

dependencies:
  - base >= 4.11 && < 10
  - rio >= 0.1.8.0

  - hadui

ghc-options:
  - -Wall

library:
  source-dirs: src
